package models

type EmployeeStruct struct {
	EmployeeId                    string
	ApplicationId                 string
	EmployeeCode                  string
	FingCode                      string
	EmployeeTypeCode              string
	EmployeeTypeGroupId           string
	EmployeeNickname              string
	EmployeeNicknameEn            string
	EmployeeName                  string
	EmployeeLastName              string
	EmployeeNameEn                string
	EmployeeLastNameEn            string
	EmployeeTitleLv               string
	EmployeeGender                string
	EmployeeForeigner             string
	CountryId                     string
	EmployeeStatus                string
	PositionId                    string
	CompanyId                     string
	BranchId                      string
	DepartmentId                  string
	DivisionId                    string
	SectionId                     string
	Mobilephone                   string
	Emailaddress                  string
	Salary                        string
	SalaryLaw                     string
	SalaryPerWeek                 string
	SalaryPerWeekTypeLv           string
	PaymentMethod                 string
	SocialInsuranceMethodLv       string
	SocialInsuranceMethodConstant string
	SocialInsuranceDeductLv       string
	TaxMethodLv                   string
	TaxMethodConstant             string
	TaxMethodRate                 string
	TaxDeductLv                   string
	TaxStartMonth                 string
	DaysPerMonth                  string
	HoursPerDay                   string
	BirthDt                       string
	IdNo                          string
	SsoNo                         string
	OptCode                       string
	PersonId                      string
	LineUserId                    string
	PlayerId                      string
	AppleId                       string
	FacebookId                    string
	GoogleId                      string
	LineTokenId                   string
	LineTokenTodolistId           string
	DeviceId                      string
	Photograph                    string
	CompanyPaymentAccountId       string
	BankId                        string
	BankBranchCode                string
	BankAccountCode               string
	BankOtherName                 string
	WorkCycleIdJson               string
	WorkCycleFormat               string
	HolidayDayJson                string
	HolidayFormat                 string
	AuthFirst                     string
	AuthSecond                    string
	ClockInout                    string
	TrialRange                    string
	EffectiveDt                   string
	BeginDt                       string
	ContractExpireDt              string
	RetirementYear                string
	SignoutFlag                   string
	SignoutRequestDt              string
	SignoutDt                     string
	OutDt                         string
	SsoOutDt                      string
	SignoutTypeFlag               string
	SignoutRemark                 string
	RoundMonthConfig              string
	RoundXtraConfig               string
	RoundOtConfig                 string
	RoundWorktimeConfig           string
	HolidayApplyConfig            string
	ImportLogId                   string
	PersonalConfig                string
	Address                       string
	Address1                      string
	Address2                      string
	Address3                      string
	Address4                      string
	Address5                      string
	Address6                      string
	Address7                      string
	Address8                      string
	Address9                      string
	CountryCode                   string
	StateCode                     string
	DistrictCode                  string
	SubdistrictCode               string
	PostCode                      string
	CurrentAddress                string
	CurrentAddress1               string
	CurrentAddress2               string
	CurrentAddress3               string
	CurrentAddress4               string
	CurrentAddress5               string
	CurrentAddress6               string
	CurrentAddress7               string
	CurrentAddress8               string
	CurrentAddress9               string
	CurrentCountryCode            string
	CurrentStateCode              string
	CurrentDistrictCode           string
	CurrentSubdistrictCode        string
	CurrentPostCode               string
	HashtagDesc                   string
	ReferenceCode1                string
	ReferenceCode2                string
	ReferenceCode3                string
	ReferenceCode4                string
	ReferenceCode5                string
	SlipEncryption                string
	BlacklistFlag                 string
	MicrosoftEntraIdId            string
	CoaAccountGroupId             string
	OrderNo                       string
	ServerId                      string
	InstanceServerId              string
	InstanceServerChannelId       string
	PublishFlag                   string
	ApproveFlag                   string
	ApproveRemark                 string
	GlobalFlag                    string
	ReadOnlyFlag                  string
	SysDelFlag                    string
	RemoteIp                      string
	LanguageCode                  string
	CreatedBy                     string
	Created                       string
	LastUpdBy                     string
	LastUpd                       string
	SsoStartMonth                 string
}
